const tasks = {
  0o0: {
    id: 0o0,
    title: 'Finish React project',
    description: 'Complete the remaining components for the React project.',
    completed: false,
    deadline: '2022-12-01',
    stakes: '$15',
  },
  0o1: {
    id: 0o1,
    title: 'Study for Math exam',
    description: 'Review chapters 4 to 6 for the upcoming Math exam.',
    completed: false,
    deadline: '2022-12-05',
    stakes: '$10',
  },
  0o2: {
    id: 0o2,
    title: 'Buy groceries',
    description: 'Buy milk, eggs, bread, and vegetables from the supermarket.',
    completed: false,
    deadline: '2022-11-30',
    stakes: '$20',
  },
  0o3: {
    id: 0o3,
    title: 'Prepare presentation',
    description: 'Prepare slides for the project presentation next week.',
    completed: false,
    deadline: '2022-12-07',
    stakes: '$15',
  },
  0o4: {
    id: 0o4,
    title: 'Write blog post',
    description: 'Write a blog post about the latest JavaScript features.',
    completed: false,
    deadline: '2022-12-10',
    stakes: '$20',
  },
  0o5: {
    id: 0o5,
    title: 'Read a book',
    description: 'Read "The Pragmatic Programmer" book.',
    completed: false,
    deadline: '2022-12-20',
    stakes: '$15',
  },
  0o6: {
    id: 0o6,
    title: 'Attend conference',
    description: 'Attend the virtual Web Development conference.',
    completed: false,
    deadline: '2022-12-22',
    stakes: '$10',
  },
  0o7: {
    id: 0o7,
    title: 'Visit doctor',
    description: 'Have a regular check-up with the doctor.',
    completed: false,
    deadline: '2022-12-23',
    stakes: '$20',
  },
  0o10: {
    id: 0o10,
    title: 'Clean the house',
    description: 'Do a general cleaning of the house.',
    completed: false,
    deadline: '2022-12-24',
    stakes: '$15',
  },
  0o11: {
    id: 0o11,
    title: 'Finish online course',
    description: 'Finish the remaining modules of the online course.',
    completed: false,
    deadline: '2022-12-25',
    stakes: '$20',
  },
  0o12: {
    id: 0o12,
    title: 'Write a report',
    description: 'Write a report about the recent project.',
    completed: false,
    deadline: '2022-12-26',
    stakes: '$15',
  },
  0o13: {
    id: 0o13,
    title: 'Prepare a meal',
    description: 'Prepare a healthy meal for dinner.',
    completed: false,
    deadline: '2022-12-27',
    stakes: '$10',
  },
  0o14: {
    id: 0o14,
    title: 'Do laundry',
    description: 'Wash and iron clothes.',
    completed: false,
    deadline: '2022-12-28',
    stakes: '$20',
  },
  0o15: {
    id: 0o15,
    title: 'Call a friend',
    description: 'Catch up with a friend over a phone call.',
    completed: false,
    deadline: '2022-12-29',
    stakes: '$15',
  },
  0o16: {
    id: 0o16,
    title: 'Go for a run',
    description: 'Do a 5km run in the park.',
    completed: false,
    deadline: '2022-12-30',
    stakes: '$10',
  },
  0o17: {
    id: 0o17,
    title: 'Plan vacation',
    description: 'Plan the itinerary for the upcoming vacation.',
    completed: false,
    deadline: '2022-12-15',
    stakes: '$15',
  },
};
export default tasks;
